require("./bootstrap");
import Swal from "sweetalert2";
import DropZone from "dropzone-vue";
import "dropzone-vue/dist/dropzone-vue.common.css";

import joinClass from "./components/modals/joinClass.vue";
import ShareAssessment from "./components/modals/ShareAssessment.vue";
import AuthForm from "./components/AuthForm.vue";
import ModuleSection from "./components/ModuleSection.vue";
import UpdateAssessment from "./components/UpdateAssessment.vue";
import CreateAssessment from "./components/CreateAssessment.vue";
import AssessmentView from "./components/AssessmentView.vue";
import CheckResponse from "./components/CheckResponse.vue";
import ExcelGrades from "./components/ExcelGrades.vue";
import MyAssessment from "./components/MyAssessment.vue";
import ManagePeople from "./components/ManagePeople.vue";
import { createApp } from "vue";
import print from "vue3-print-nb";
const app = createApp({});
app.config.globalProperties.$Swal = Swal;
app.component("join-class", joinClass);
app.component("share-assessment", ShareAssessment);
app.component("auth-form", AuthForm);
app.component("module-section", ModuleSection);
app.component("update-assessment", UpdateAssessment);
app.component("create-assessment", CreateAssessment);
app.component("assessment-response", AssessmentView);
app.component("check-response", CheckResponse);
app.component("excel-grades", ExcelGrades);
app.component("my-assessment", MyAssessment);
app.component("manage-people", ManagePeople);
app.use(DropZone);
app.use(print);
app.mount("#app");
